### ISSUE TITLE
Push Notifications not Working

### ISSUE THREAD

**Issue by awaistariq** [sinch/ios-managed-push-tutorial#1]
I have followed all the steps for managed push notifications tutorial. After for around a week of trying I am unable to receive call push notification. It is fine if application is open but never works with push notification.

Let me know if you need code / settings.

**Comment by rahul-apple** [comment]
@awaistariq   Hai , I am too having the Same issue.If the App is completely terminated state The push notifications are not coming(The First Push notification only ).

**Comment by avitruk** [comment]
@awaistariq seems it sames to me
